### ISSUE TITLE
Unityでレコードを再生するにはどうしたらいいのでしょうか？

### ISSUE THREAD

**Issue by tomtomtong** [drumath2237/ARGeoRecorder#1]
Unityでレコードを再生するにはどうしたらいいですか？何か例はありますか？

お疲れ様でした。

How can I play records in Unity? Is there any example?

Thank you for your work.

**Comment by drumath2237** [comment]
@tomtomtong 
Hi. Thanks for seeing this project.

Currently, ARCore Recording & Playback API doesn't support running in Unity Editor, I think.
In order to playback recorded mp4 file,  ARCore supported device is needed.

**Comment by drumath2237** [comment]
I'll close this issue, but you can reopen freely when you want to ask more. 👋
